"""
Synthetic image-caption data for Module 8 (PROVIDED — you do not edit this file).

The goal is to make the multimodal bridge *visible* on a laptop CPU, so the images
are deliberately tiny and the language is deliberately small. Every scene is a
32x32 RGB image with two solid colored shapes on a black background: one in the top
half, one in the bottom half. The caption names both and their spatial relation:

    "red square above blue circle"

From the same scene we also derive a few grounded visual questions, e.g.

    "what color is on top?"    -> "red"
    "what shape is on bottom?" -> "circle"

Colors, shapes, and the one relation ("above") are the whole visual vocabulary, so a
tiny vision encoder can learn to align images with captions and a tiny language model
can learn to answer from a projected image embedding. Because the caption space has
3 colors x 3 shapes x 3 colors x 3 shapes = 81 distinct top/bottom combinations, a
batch of scenes almost always has distinct captions — which is what the CLIP-style
contrastive objective assumes (one correct caption per image, one correct image per
caption).

Rendering uses plain tensors (no image libraries); matplotlib is only used later, by
visualization.py, to draw the sample grid and the retrieval heatmap.
"""

from __future__ import annotations

from pathlib import Path

import torch

IMG_SIZE = 32
HALF = IMG_SIZE // 2

# The entire visual vocabulary.
COLORS: dict[str, tuple[float, float, float]] = {
    "red": (0.90, 0.15, 0.15),
    "green": (0.15, 0.75, 0.20),
    "blue": (0.20, 0.40, 0.95),
}
SHAPES = ["square", "circle", "triangle"]
COLOR_NAMES = list(COLORS)


# ---------------------------------------------------------------------------
# Rasterizers: draw one filled shape into a (3, H, W) canvas region.
# ---------------------------------------------------------------------------

def _color_tensor(name: str) -> torch.Tensor:
    return torch.tensor(COLORS[name], dtype=torch.float32).view(3, 1, 1)


def _draw_shape(canvas: torch.Tensor, shape: str, color: str, cy: int, cx: int, r: int) -> None:
    """Paint one shape of radius ~r centered at (cy, cx) into canvas (in place)."""
    H, W = canvas.shape[1], canvas.shape[2]
    ys = torch.arange(H).view(H, 1).float()
    xs = torch.arange(W).view(1, W).float()
    dy = ys - cy
    dx = xs - cx
    if shape == "square":
        mask = (dy.abs() <= r) & (dx.abs() <= r)
    elif shape == "circle":
        mask = (dy * dy + dx * dx) <= (r * r)
    elif shape == "triangle":
        # Upward triangle: widens from the apex (top) down to the base.
        frac = (dy + r) / (2 * r)              # 0 at apex, 1 at base
        halfw = frac * r
        mask = (dy >= -r) & (dy <= r) & (dx.abs() <= halfw)
    else:
        raise ValueError(f"unknown shape {shape}")
    color_t = _color_tensor(color)
    mask3 = mask.unsqueeze(0)                    # (1, H, W)
    canvas[:] = torch.where(mask3, color_t, canvas)


def render_scene(top: tuple[str, str], bottom: tuple[str, str], jitter: torch.Tensor) -> torch.Tensor:
    """Render one two-shape scene as a (3, 32, 32) float tensor in [0, 1].

    `top`/`bottom` are (color, shape) pairs; `jitter` is a small (2,) integer offset
    that shifts the shapes horizontally so scenes with the same caption still differ
    pixel-for-pixel (held-out images are never seen exactly during training).
    """
    canvas = torch.zeros(3, IMG_SIZE, IMG_SIZE, dtype=torch.float32)
    r = 6
    jx_top, jx_bot = int(jitter[0]), int(jitter[1])
    _draw_shape(canvas, top[1], top[0], cy=HALF // 2 + 1, cx=HALF + jx_top, r=r)
    _draw_shape(canvas, bottom[1], bottom[0], cy=IMG_SIZE - HALF // 2 - 1, cx=HALF + jx_bot, r=r)
    return canvas


# ---------------------------------------------------------------------------
# Scene sampling and the language derived from each scene.
# ---------------------------------------------------------------------------

def caption_for(top: tuple[str, str], bottom: tuple[str, str]) -> str:
    """The full caption: '<c1> <s1> above <c2> <s2>'."""
    return f"{top[0]} {top[1]} above {bottom[0]} {bottom[1]}"


def questions_for(top: tuple[str, str], bottom: tuple[str, str]) -> list[tuple[str, str]]:
    """Grounded (question, answer) pairs derived from the scene."""
    return [
        ("what color is on top?", top[0]),
        ("what color is on bottom?", bottom[0]),
        ("what shape is on top?", top[1]),
        ("what shape is on bottom?", bottom[1]),
    ]


def _all_pairs() -> list[tuple[str, str]]:
    return [(c, s) for c in COLOR_NAMES for s in SHAPES]


def build_dataset(seed: int = 0, n_train: int = 340, n_eval: int = 60) -> dict:
    """Build the full synthetic dataset as a dict of tensors and python lists.

    Returns a dict with, for each split, an image tensor of shape (N, 3, 32, 32), the
    caption strings, and the (color, shape) top/bottom labels used to derive visual
    questions. Splits are disjoint by (scene, jitter) so eval images are never trained
    on, but captions may recur — the test is whether grounding *generalizes* to new
    pixels, not whether captions were memorized.
    """
    rng = torch.Generator().manual_seed(seed)
    pairs = _all_pairs()
    n_total = n_train + n_eval

    scenes: list[tuple[tuple[str, str], tuple[str, str], torch.Tensor]] = []
    seen: set[tuple] = set()
    while len(scenes) < n_total:
        ti = int(torch.randint(len(pairs), (1,), generator=rng))
        bi = int(torch.randint(len(pairs), (1,), generator=rng))
        jitter = torch.randint(-3, 4, (2,), generator=rng)
        key = (ti, bi, int(jitter[0]), int(jitter[1]))
        if key in seen:
            continue
        seen.add(key)
        scenes.append((pairs[ti], pairs[bi], jitter))

    def pack(subset) -> dict:
        images = torch.stack([render_scene(t, b, j) for (t, b, j) in subset])
        return {
            "images": images,
            "captions": [caption_for(t, b) for (t, b, _) in subset],
            "top": [list(t) for (t, _, _) in subset],
            "bottom": [list(b) for (_, b, _) in subset],
        }

    return {"train": pack(scenes[:n_train]), "eval": pack(scenes[n_train:])}


def save_dataset(data: dict, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(data, path)


def load_dataset(path: Path) -> dict:
    return torch.load(path, weights_only=False)


if __name__ == "__main__":
    # Regenerate the bundled dataset.
    out = Path(__file__).resolve().parent.parent / "data" / "shapes_dataset.pt"
    data = build_dataset()
    save_dataset(data, out)
    n_tr = data["train"]["images"].shape[0]
    n_ev = data["eval"]["images"].shape[0]
    print(f"Wrote {out}  (train={n_tr}, eval={n_ev}, image={tuple(data['train']['images'].shape[1:])})")
