"""
Tokenizer for Module 8 (PROVIDED — you do not edit this file).

Identical to the Module 6/7 tokenizer: the 65-character base vocabulary from the
Module 5 checkpoint plus four atomic special tokens, each a single id:

  <|user|>       - starts a user turn
  <|assistant|>  - starts an assistant turn
  <|end|>        - ends a turn
  <|pad|>        - padding token

Total vocab = 69. The instruct checkpoint the multimodal bridge starts from was
trained with exactly this vocabulary, so the ids line up. Our synthetic captions and
visual questions use only lowercase letters, spaces, and "?", all of which are in the
base vocabulary.
"""

from __future__ import annotations

SPECIAL_TOKENS = ["<|user|>", "<|assistant|>", "<|end|>", "<|pad|>"]


def build_vocab(base_stoi: dict[str, int]) -> tuple[dict[str, int], dict[int, str]]:
    """Return expanded stoi/itos with special tokens appended at the end."""
    stoi = dict(base_stoi)
    itos = {i: c for c, i in base_stoi.items()}
    for tok in SPECIAL_TOKENS:
        idx = len(stoi)
        stoi[tok] = idx
        itos[idx] = tok
    return stoi, itos


def encode(text: str, stoi: dict[str, int]) -> list[int]:
    """Encode a plain string into token IDs (character by character)."""
    return [stoi[c] for c in text]


def decode(ids: "list[int] | object", itos: dict[int, str]) -> str:
    """Decode token IDs back to a string, preserving special tokens as literals."""
    import torch
    if isinstance(ids, torch.Tensor):
        ids = ids.tolist()
    return "".join(itos.get(int(i), "?") for i in ids)
