"""
Module 8: TinyGPT (PROVIDED — you do not edit this file).

The same decoder-only model used in Modules 5, 6, and 7. Here it plays the role of
the language model at the end of the multimodal bridge: we prepend a few *visual*
prefix embeddings to the text-token embeddings and let the transformer caption or
answer from them.

Because the visual prefix is a sequence of continuous vectors (not token ids), the
model needs a forward path that consumes embeddings directly. `forward_embeds` does
exactly that: it takes an already-built (B, L, n_embd) tensor, adds positional
embeddings, runs the transformer blocks, and returns logits. `forward` (the token-id
path) is unchanged from Module 7.

This file gives you the model, both forward paths, an autoregressive sampler
(`generate`), and a loader for the bundled instruct checkpoint (`load_instruct_model`).
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F


@dataclass
class GPTConfig:
    """All the knobs that define the model's size."""
    vocab_size: int          # how many distinct tokens (characters + specials)
    block_size: int = 128    # context length
    n_layer: int = 4         # how many transformer blocks are stacked
    n_head: int = 4          # how many attention heads per block
    n_embd: int = 128        # width of each token vector
    dropout: float = 0.0     # dropout probability (0 for RL: we want deterministic forwards)


class CausalSelfAttention(nn.Module):
    """Multi-head self-attention with a causal mask (no peeking at the future)."""

    def __init__(self, cfg: GPTConfig) -> None:
        super().__init__()
        assert cfg.n_embd % cfg.n_head == 0
        self.n_head = cfg.n_head
        self.n_embd = cfg.n_embd
        self.c_attn = nn.Linear(cfg.n_embd, 3 * cfg.n_embd)
        self.c_proj = nn.Linear(cfg.n_embd, cfg.n_embd)
        self.attn_dropout = nn.Dropout(cfg.dropout)
        self.resid_dropout = nn.Dropout(cfg.dropout)
        self.register_buffer(
            "mask",
            torch.tril(torch.ones(cfg.block_size, cfg.block_size)).view(
                1, 1, cfg.block_size, cfg.block_size
            ),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        B, T, C = x.shape
        q, k, v = self.c_attn(x).split(self.n_embd, dim=2)
        head_size = C // self.n_head
        q = q.view(B, T, self.n_head, head_size).transpose(1, 2)
        k = k.view(B, T, self.n_head, head_size).transpose(1, 2)
        v = v.view(B, T, self.n_head, head_size).transpose(1, 2)
        att = (q @ k.transpose(-2, -1)) * (1.0 / math.sqrt(head_size))
        att = att.masked_fill(self.mask[:, :, :T, :T] == 0, float("-inf"))
        att = F.softmax(att, dim=-1)
        att = self.attn_dropout(att)
        y = att @ v
        y = y.transpose(1, 2).contiguous().view(B, T, C)
        return self.resid_dropout(self.c_proj(y))


class MLP(nn.Module):
    """Position-wise feed-forward network: widen to 4x, GELU, project back."""

    def __init__(self, cfg: GPTConfig) -> None:
        super().__init__()
        self.fc = nn.Linear(cfg.n_embd, 4 * cfg.n_embd)
        self.proj = nn.Linear(4 * cfg.n_embd, cfg.n_embd)
        self.dropout = nn.Dropout(cfg.dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.dropout(self.proj(F.gelu(self.fc(x))))


class Block(nn.Module):
    """One transformer block: pre-norm attention and FFN, each with a residual."""

    def __init__(self, cfg: GPTConfig) -> None:
        super().__init__()
        self.ln1 = nn.LayerNorm(cfg.n_embd)
        self.attn = CausalSelfAttention(cfg)
        self.ln2 = nn.LayerNorm(cfg.n_embd)
        self.mlp = MLP(cfg)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = x + self.attn(self.ln1(x))
        x = x + self.mlp(self.ln2(x))
        return x


class TinyGPT(nn.Module):
    """A small decoder-only language model: embeddings -> blocks -> LM head."""

    def __init__(self, cfg: GPTConfig) -> None:
        super().__init__()
        self.cfg = cfg
        self.block_size = cfg.block_size
        self.token_embed = nn.Embedding(cfg.vocab_size, cfg.n_embd)
        self.pos_embed = nn.Embedding(cfg.block_size, cfg.n_embd)
        self.drop = nn.Dropout(cfg.dropout)
        self.blocks = nn.ModuleList([Block(cfg) for _ in range(cfg.n_layer)])
        self.ln_f = nn.LayerNorm(cfg.n_embd)
        self.lm_head = nn.Linear(cfg.n_embd, cfg.vocab_size, bias=False)
        self.lm_head.weight = self.token_embed.weight

    def forward(self, idx: torch.Tensor) -> torch.Tensor:
        B, T = idx.shape
        pos = torch.arange(T, dtype=torch.long, device=idx.device)
        x = self.drop(self.token_embed(idx) + self.pos_embed(pos))
        for block in self.blocks:
            x = block(x)
        x = self.ln_f(x)
        return self.lm_head(x)

    def forward_embeds(self, inputs_embeds: torch.Tensor) -> torch.Tensor:
        """Run the transformer from pre-built input embeddings instead of token ids.

        `inputs_embeds` has shape (B, L, n_embd) and already contains whatever the
        caller wants in each slot — visual prefix vectors, text-token embeddings, or
        a concatenation of both. We only add positional embeddings and run the stack.
        This is the entry point the multimodal bridge uses so a projected image
        embedding can sit in the sequence exactly where a token embedding would.
        """
        B, T, C = inputs_embeds.shape
        pos = torch.arange(T, dtype=torch.long, device=inputs_embeds.device)
        x = self.drop(inputs_embeds + self.pos_embed(pos))
        for block in self.blocks:
            x = block(x)
        x = self.ln_f(x)
        return self.lm_head(x)

    def embed_tokens(self, idx: torch.Tensor) -> torch.Tensor:
        """Look up token embeddings only (no positional add, no blocks).

        The bridge needs raw text-token embeddings so it can concatenate the visual
        prefix in front of them before calling `forward_embeds`.
        """
        return self.token_embed(idx)

    def num_params(self) -> int:
        return sum(p.numel() for p in self.parameters())


@torch.no_grad()
def generate(
    model: nn.Module,
    idx: torch.Tensor,
    max_new_tokens: int,
    block_size: int,
    temperature: float = 1.0,
    greedy: bool = False,
    generator: torch.Generator | None = None,
) -> torch.Tensor:
    """Autoregressively extend idx by sampling (or argmax-ing) max_new_tokens tokens.

    With greedy=True the model takes the most likely token at each step (used for a
    deterministic before/after accuracy check). Otherwise it samples at `temperature`
    (used to draw a diverse group of completions for GRPO).
    """
    was_training = model.training
    model.eval()
    for _ in range(max_new_tokens):
        idx_cond = idx[:, -block_size:]
        logits = model(idx_cond)[:, -1, :]
        if greedy:
            next_id = logits.argmax(dim=-1, keepdim=True)
        else:
            probs = F.softmax(logits / temperature, dim=-1)
            next_id = torch.multinomial(probs, num_samples=1, generator=generator)
        idx = torch.cat([idx, next_id], dim=1)
    if was_training:
        model.train()
    return idx


def load_instruct_model(ckpt_path: str | Path) -> tuple[TinyGPT, dict[str, int], dict[int, str]]:
    """Load the bundled Module 6 instruct checkpoint (LoRA already merged).

    Returns the model, the string-to-id map, and the id-to-string map. The
    checkpoint already carries the full 69-token vocabulary, so nothing is resized.
    """
    ckpt = torch.load(ckpt_path, weights_only=False)
    raw_cfg = ckpt["config"]
    cfg = GPTConfig(**raw_cfg) if isinstance(raw_cfg, dict) else raw_cfg
    cfg.dropout = 0.0
    model = TinyGPT(cfg)
    model.load_state_dict(ckpt["state_dict"], strict=True)
    model.eval()
    return model, ckpt["stoi"], ckpt["itos"]
