"""
Vision tower and text encoder for Module 8 (PROVIDED — you do not edit this file).

These modules hold the *learnable parameters* the exercise steps operate on; the
steps themselves (in exercise.py) are the interesting one-liners. The split mirrors
Module 7: the runner owns the parameters and the loop, and calls your functions to do
the actual math.

  VisionEncoder  - patch projection, learned patch position embeddings, a small
                   provided transformer that mixes patches, and nothing else. Your
                   steps do the patchify -> flatten -> project -> add-positions ->
                   pool pipeline around it, producing one image embedding.
  TextEncoder    - a tiny char-level transformer that pools a caption into an
                   embedding of the SAME width as the image embedding, so the two can
                   be compared in a shared space (this is the "text tower" of CLIP).
  Projector      - the multimodal bridge: a single Linear that maps one pooled image
                   embedding into K visual prefix vectors at the language model's
                   width.

Widths are deliberately tiny so everything trains on a CPU in a couple of minutes.
"""

from __future__ import annotations

import torch
import torch.nn as nn

from model import Block, GPTConfig

# ---- Fixed dimensions for the whole exercise -----------------------------------
IMG_SIZE = 32
PATCH_SIZE = 8                       # 8x8 patches
N_PATCHES = (IMG_SIZE // PATCH_SIZE) ** 2   # 4 x 4 = 16 patches
PATCH_DIM = PATCH_SIZE * PATCH_SIZE * 3     # 8*8*3 = 192 values per patch
D_EMBED = 64                         # shared vision/text embedding width (CLIP space)
PREFIX_LEN = 4                       # number of visual prefix tokens fed to the LM


def _mixer_config(width: int, n_patches: int, n_layer: int, n_head: int) -> GPTConfig:
    """A GPTConfig reused only for its Block (attention + MLP) at a small width."""
    return GPTConfig(
        vocab_size=1,               # unused; we never build a token embedding here
        block_size=n_patches,
        n_layer=n_layer,
        n_head=n_head,
        n_embd=width,
        dropout=0.0,
    )


class VisionEncoder(nn.Module):
    """Turns an image into patch features and mixes them; your steps pool them.

    Attributes used by the exercise steps:
      patch_proj : Linear(PATCH_DIM -> D_EMBED)   (step 3 applies this)
      pos_embed  : Parameter(1, N_PATCHES, D_EMBED)  (step 4 adds this)
    `mix` is a provided self-attention stack that lets patches share information
    before you pool them (step 5), so the pooled vector can encode relations like
    "the top shape is a triangle", not just average color.
    """

    def __init__(self) -> None:
        super().__init__()
        self.patch_size = PATCH_SIZE
        self.patch_proj = nn.Linear(PATCH_DIM, D_EMBED)
        self.pos_embed = nn.Parameter(torch.zeros(1, N_PATCHES, D_EMBED))
        nn.init.normal_(self.pos_embed, std=0.02)
        cfg = _mixer_config(D_EMBED, N_PATCHES, n_layer=2, n_head=4)
        self.blocks = nn.ModuleList([Block(cfg) for _ in range(cfg.n_layer)])
        self.ln = nn.LayerNorm(D_EMBED)

    def mix(self, x: torch.Tensor) -> torch.Tensor:
        """Provided patch mixing: run the small transformer over the patch sequence."""
        for block in self.blocks:
            x = block(x)
        return self.ln(x)

    def num_params(self) -> int:
        return sum(p.numel() for p in self.parameters())


class TextEncoder(nn.Module):
    """The CLIP text tower (PROVIDED in full): caption ids -> one pooled embedding.

    A char embedding, learned positions, a small transformer, then a masked mean over
    the real (non-pad) tokens, projected to D_EMBED. Callable as `text_encoder(ids)`.
    """

    def __init__(self, vocab_size: int, pad_id: int, max_len: int = 40) -> None:
        super().__init__()
        self.pad_id = pad_id
        self.max_len = max_len
        self.tok_embed = nn.Embedding(vocab_size, D_EMBED)
        self.pos_embed = nn.Embedding(max_len, D_EMBED)
        cfg = _mixer_config(D_EMBED, max_len, n_layer=2, n_head=4)
        self.blocks = nn.ModuleList([Block(cfg) for _ in range(cfg.n_layer)])
        self.ln = nn.LayerNorm(D_EMBED)

    def forward(self, ids: torch.Tensor) -> torch.Tensor:
        B, T = ids.shape
        pos = torch.arange(T, device=ids.device)
        x = self.tok_embed(ids) + self.pos_embed(pos)
        for block in self.blocks:
            x = block(x)
        x = self.ln(x)
        keep = (ids != self.pad_id).float().unsqueeze(-1)      # (B, T, 1)
        pooled = (x * keep).sum(dim=1) / keep.sum(dim=1).clamp(min=1.0)
        return pooled                                          # (B, D_EMBED)

    def num_params(self) -> int:
        return sum(p.numel() for p in self.parameters())


class Projector(nn.Module):
    """The multimodal bridge (PROVIDED parameters; step 11 uses `to_prefix`).

    `to_prefix` maps one pooled image embedding (D_EMBED) to PREFIX_LEN * d_llm
    numbers; your step reshapes those into PREFIX_LEN visual prefix vectors at the
    language model's width, ready to sit in front of the text-token embeddings.
    """

    def __init__(self, d_llm: int, prefix_len: int = PREFIX_LEN) -> None:
        super().__init__()
        self.prefix_len = prefix_len
        self.d_llm = d_llm
        self.to_prefix = nn.Linear(D_EMBED, prefix_len * d_llm)

    def num_params(self) -> int:
        return sum(p.numel() for p in self.parameters())
