"""
Module 8 plotting (PROVIDED — you do not edit this file).

Two figures make the exercise concrete:

  save_image_grid      - a grid of sample synthetic scenes with their captions, so you
                         can see exactly what the model is aligning.
  save_retrieval_heatmap - the image-text similarity matrix for one batch, with the
                         diagonal (the matched pairs) standing out when CLIP has
                         learned. A bright diagonal means retrieval works.

Matplotlib uses the non-interactive Agg backend so everything runs headless.
"""

from __future__ import annotations

from pathlib import Path

import torch

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402


def _to_hwc(image: torch.Tensor):
    """(3, H, W) float tensor -> (H, W, 3) numpy for imshow."""
    return image.permute(1, 2, 0).clamp(0, 1).cpu().numpy()


def save_image_grid(
    images: torch.Tensor,
    captions: list[str],
    out_path: str | Path,
    rows: int = 3,
    cols: int = 4,
) -> None:
    """Save a rows x cols grid of sample scenes titled with their captions."""
    n = min(rows * cols, images.shape[0])
    fig, axes = plt.subplots(rows, cols, figsize=(cols * 2.2, rows * 2.4), dpi=120)
    axes = axes.reshape(-1)
    for i in range(rows * cols):
        ax = axes[i]
        ax.axis("off")
        if i < n:
            ax.imshow(_to_hwc(images[i]), interpolation="nearest")
            ax.set_title(captions[i], fontsize=8)
    fig.suptitle("Synthetic scenes and their captions", fontsize=12)
    fig.tight_layout()
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path)
    plt.close(fig)


def save_retrieval_heatmap(
    sim: torch.Tensor,
    captions: list[str],
    out_path: str | Path,
    max_n: int = 10,
) -> None:
    """Save the image-text similarity matrix as a heatmap (diagonal = matched pairs)."""
    n = min(max_n, sim.shape[0])
    m = sim[:n, :n].detach().cpu().numpy()
    fig, ax = plt.subplots(figsize=(6.5, 5.6), dpi=120)
    im = ax.imshow(m, cmap="viridis", aspect="auto")
    ax.set_xlabel("caption index (text)")
    ax.set_ylabel("image index")
    ax.set_title("Image-text similarity: a bright diagonal means retrieval works")
    ax.set_xticks(range(n))
    ax.set_yticks(range(n))
    # Outline the matched diagonal cells.
    for i in range(n):
        ax.add_patch(plt.Rectangle((i - 0.5, i - 0.5), 1, 1, fill=False,
                                   edgecolor="white", linewidth=1.5))
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04, label="similarity")
    fig.tight_layout()
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path)
    plt.close(fig)
