"""
Verifiable task data for Module 7 (PROVIDED — you do not edit this file).

The task is string reversal: a prompt "reverse: abcde" has the verified answer
"edcba". There are no human labels and no reward model; the reward is computed by a
Python function (your `verifiable_reward`), which is the whole idea of RLVR.

This module is the single source of truth for the word splits, so the instruct
checkpoint (trained by solution/src/make_instruct_checkpoint.py) and the RL prompts
never overlap:

  - SFT words   : used only to finetune the instruct model (held out from RL)
  - RL-train    : prompts GRPO samples and learns from
  - eval        : held-out prompts used only to measure before/after accuracy

All three are disjoint, and every word is `WORD_LENGTH` lowercase letters (all in
the base vocabulary), so the same chat template and character vocabulary as Module 6
carry over.
"""

from __future__ import annotations

import json
import random
from pathlib import Path

WORD_LENGTH = 5
LETTERS = "abcdefghijklmnopqrstuvwxyz"

N_SFT = 600      # words used to teach reverse during SFT (not seen by RL)
N_TRAIN = 256    # RL training prompts (diverse enough that GRPO improves the general skill)
N_EVAL = 40      # held-out evaluation prompts


def _unique_words(seed: int, count: int, length: int) -> list[str]:
    """Deterministically draw `count` distinct lowercase strings of a given length."""
    rng = random.Random(seed)
    words: set[str] = set()
    while len(words) < count:
        words.add("".join(rng.choice(LETTERS) for _ in range(length)))
    out = sorted(words)
    rng.shuffle(out)
    return out


def word_splits(seed: int = 0) -> dict[str, list[str]]:
    """Return disjoint {'sft', 'train', 'eval'} word lists of length WORD_LENGTH."""
    pool = _unique_words(seed, N_SFT + N_TRAIN + N_EVAL, WORD_LENGTH)
    return {
        "sft": pool[:N_SFT],
        "train": pool[N_SFT:N_SFT + N_TRAIN],
        "eval": pool[N_SFT + N_TRAIN:],
    }


def generate_prompts(seed: int = 0) -> list[dict[str, str]]:
    """Build the RL prompt records (train + eval) as {prompt, answer, split}."""
    splits = word_splits(seed)
    records: list[dict[str, str]] = []
    for split in ("train", "eval"):
        for w in splits[split]:
            records.append({"prompt": f"reverse: {w}", "answer": w[::-1], "split": split})
    return records


def save_prompts(records: list[dict[str, str]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for item in records:
            f.write(json.dumps(item) + "\n")


def load_prompts(path: Path) -> list[dict[str, str]]:
    out = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                out.append(json.loads(line))
    return out


if __name__ == "__main__":
    # Regenerate the bundled prompt file.
    out_path = Path(__file__).resolve().parent.parent / "data" / "verify_prompts.jsonl"
    save_prompts(generate_prompts(), out_path)
    print(f"Wrote {out_path}")
