"""
Module 11 data loading (PROVIDED; you do not edit this file).

Two files, both JSONL (one JSON object per line):
  articles.jsonl  the corpus: 48 support articles, each {id, title, body}
  queries.jsonl   the labeled queries: {id, category, text, relevant_ids}
"""

from __future__ import annotations

import json
from pathlib import Path


def load_jsonl(path: str | Path) -> list[dict]:
    """Read a JSONL file into a list of dicts, skipping blank lines."""
    records = []
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def article_text(article: dict) -> str:
    """The text both retrievers index: the title and the body together."""
    return article["title"] + ". " + article["body"]
