"""
Module 11 sentence encoder (PROVIDED; you do not edit this file).

Wraps the bundled MiniLM encoder (data/encoder/, 23M parameters, ~44MB on disk)
so the rest of the exercise never touches the transformer directly. The model is
all-MiniLM-L6-v2: a 6-layer BERT-style encoder finetuned contrastively on a
billion sentence pairs, the same objective Module 8's CLIP used, with text on
both sides instead of text and images. It runs on CPU and needs no network
access; everything loads from the local files.

The weights in data/encoder/ are a verbatim copy of
https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2 (Apache-2.0),
committed to this repo so the exercise works offline.

The one thing this file deliberately does NOT do is pooling. The encoder emits
one 384-dimensional vector per token, and turning those into one vector per
document is step 6 in exercise.py.
"""

from __future__ import annotations

import os
from pathlib import Path

# Everything is bundled; never let transformers try the network.
os.environ.setdefault("HF_HUB_OFFLINE", "1")
os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")

import numpy as np
import torch
from transformers import AutoModel, AutoTokenizer, logging as hf_logging

hf_logging.set_verbosity_error()  # silence the checkpoint-loading progress noise

BATCH_SIZE = 16      # articles per forward pass; padding within a batch only
MAX_TOKENS = 256     # longest article is ~100 tokens, so nothing is truncated


class SentenceEncoder:
    """The bundled MiniLM, exposed as text -> (per-token vectors, mask)."""

    def __init__(self, encoder_dir: str | Path):
        self.tokenizer = AutoTokenizer.from_pretrained(encoder_dir)
        # Weights are stored in fp16 to keep the download small; compute in fp32.
        self.model = (AutoModel.from_pretrained(encoder_dir, dtype=torch.float16)
                      .float().eval())

    @torch.no_grad()
    def encode(self, texts: list[str]) -> list[tuple[np.ndarray, np.ndarray]]:
        """Run the encoder over texts, in batches.

        Returns one (token_vectors, attention_mask) pair per text:
          token_vectors   shape (tokens, 384), one vector per token, fp64
          attention_mask  shape (tokens,), 1.0 for real tokens, 0.0 for padding

        Texts in a batch are padded to the batch's longest text, which is why
        the mask exists: mean pooling (step 6) must ignore the padding.
        """
        results: list[tuple[np.ndarray, np.ndarray]] = []
        for start in range(0, len(texts), BATCH_SIZE):
            batch_texts = texts[start:start + BATCH_SIZE]
            batch = self.tokenizer(batch_texts, padding=True, truncation=True,
                                   max_length=MAX_TOKENS, return_tensors="pt")
            hidden = self.model(**batch).last_hidden_state  # (batch, tokens, 384)
            for row in range(len(batch_texts)):
                results.append((
                    hidden[row].double().numpy(),
                    batch["attention_mask"][row].double().numpy(),
                ))
        return results
