"""
Module 11 plotting (PROVIDED; you do not edit this file).

One figure: a grouped bar chart of recall@3 per query category for the two
retrievers, with the overall score beside it. The picture is the argument:
the two overall bars are close, and the per-category bars are not, which is
the same lesson Module 9's per-task chart taught about models. Matplotlib
uses the non-interactive Agg backend so it runs headless on a laptop.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

SPARSE_COLOR = "#1f6feb"
DENSE_COLOR = "#d29922"


def save_category_comparison(
    categories: list[str],
    sparse_scores: list[float],
    dense_scores: list[float],
    out_path: str | Path,
    sparse_overall: float | None = None,
    dense_overall: float | None = None,
) -> None:
    """Grouped bar chart of recall@3 per category for both retrievers."""
    labels = list(categories)
    left = list(sparse_scores)
    right = list(dense_scores)
    if sparse_overall is not None and dense_overall is not None:
        labels = labels + ["overall"]
        left = left + [sparse_overall]
        right = right + [dense_overall]

    positions = range(len(labels))
    width = 0.38

    fig, ax = plt.subplots(figsize=(8, 4.5), dpi=120)
    bars_a = ax.bar([p - width / 2 for p in positions], left, width,
                    color=SPARSE_COLOR, label="sparse (TF-IDF)")
    bars_b = ax.bar([p + width / 2 for p in positions], right, width,
                    color=DENSE_COLOR, label="dense (MiniLM embeddings)")

    for bars in (bars_a, bars_b):
        for bar in bars:
            ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.02,
                    f"{bar.get_height():.0%}", ha="center", va="bottom", fontsize=8)

    if sparse_overall is not None:
        ax.axvline(len(labels) - 1.5, color="#888888", linewidth=1, linestyle=":")

    ax.set_xticks(list(positions))
    ax.set_xticklabels(labels)
    ax.set_ylabel("recall@3")
    ax.set_ylim(0, 1.12)
    ax.set_yticks([0.0, 0.25, 0.5, 0.75, 1.0])
    ax.set_yticklabels(["0%", "25%", "50%", "75%", "100%"])
    ax.set_title("Recall@3 by query category: neither retriever dominates")
    ax.grid(True, axis="y", alpha=0.3)
    ax.set_axisbelow(True)
    # Below the axes, so it can never sit on top of a tall bar's value label.
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.09), ncol=2, frameon=False)

    fig.tight_layout()
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path)
    plt.close(fig)
