"""Plotting helper for the concurrency benchmark. Internal plumbing; students
do not edit this file."""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")  # write files without needing a display
import matplotlib.pyplot as plt  # noqa: E402


def save_throughput_figure(results: list[dict], path: Path) -> None:
    """Plot total throughput and per-stream speed against concurrency.

    Each entry in `results` is {"n": concurrency, "total": tokens/sec across
    all requests, "per_stream": mean tokens/sec of one request}.
    """
    ns = [r["n"] for r in results]
    totals = [r["total"] for r in results]
    per_stream = [r["per_stream"] for r in results]

    fig, ax = plt.subplots(figsize=(7, 4.5))
    ax.plot(ns, totals, marker="o", linewidth=2, color="#4c9be8",
            label="total throughput (operator)")
    ax.plot(ns, per_stream, marker="s", linewidth=2, color="#e8834c",
            label="per-stream rate (one user)")
    ax.set_xlabel("concurrent requests")
    ax.set_ylabel("tokens per second")
    ax.set_title("Batching: the machine speeds up, each user barely slows down")
    ax.set_xticks(ns)
    ax.grid(alpha=0.3)
    ax.legend()
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)
