"""
Module 6: TinyGPT + LoRA (PROVIDED — you do not edit this file).

Copies the Module 5 decoder-only model verbatim and adds LoRA machinery:
LoRALinear, inject_lora, freeze_base_, merge_lora_weight, merge_lora,
and load_base_model (vocab expansion for special tokens).
"""

from __future__ import annotations

import math
import sys
from dataclasses import dataclass
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F

# Allow importing the student's exercise.py (it defines lora_forward_delta,
# freeze_base_param, and merge_lora_weight that this file calls).
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from exercise import (  # noqa: E402
    lora_forward_delta,
    freeze_base_param,
    merge_lora_weight,
)


@dataclass
class GPTConfig:
    """All the knobs that define the model's size."""
    vocab_size: int          # how many distinct tokens (characters + specials)
    block_size: int = 128    # context length
    n_layer: int = 4         # how many transformer blocks are stacked
    n_head: int = 4          # how many attention heads per block
    n_embd: int = 128        # width of each token vector
    dropout: float = 0.1     # dropout probability used during training


class CausalSelfAttention(nn.Module):
    """Multi-head self-attention with a causal mask (no peeking at the future)."""

    def __init__(self, cfg: GPTConfig) -> None:
        super().__init__()
        assert cfg.n_embd % cfg.n_head == 0
        self.n_head = cfg.n_head
        self.n_embd = cfg.n_embd
        self.c_attn = nn.Linear(cfg.n_embd, 3 * cfg.n_embd)
        self.c_proj = nn.Linear(cfg.n_embd, cfg.n_embd)
        self.attn_dropout = nn.Dropout(cfg.dropout)
        self.resid_dropout = nn.Dropout(cfg.dropout)
        self.register_buffer(
            "mask",
            torch.tril(torch.ones(cfg.block_size, cfg.block_size)).view(
                1, 1, cfg.block_size, cfg.block_size
            ),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        B, T, C = x.shape
        q, k, v = self.c_attn(x).split(self.n_embd, dim=2)
        head_size = C // self.n_head
        q = q.view(B, T, self.n_head, head_size).transpose(1, 2)
        k = k.view(B, T, self.n_head, head_size).transpose(1, 2)
        v = v.view(B, T, self.n_head, head_size).transpose(1, 2)
        att = (q @ k.transpose(-2, -1)) * (1.0 / math.sqrt(head_size))
        att = att.masked_fill(self.mask[:, :, :T, :T] == 0, float("-inf"))
        att = F.softmax(att, dim=-1)
        att = self.attn_dropout(att)
        y = att @ v
        y = y.transpose(1, 2).contiguous().view(B, T, C)
        return self.resid_dropout(self.c_proj(y))


class MLP(nn.Module):
    """Position-wise feed-forward network: widen to 4x, GELU, project back."""

    def __init__(self, cfg: GPTConfig) -> None:
        super().__init__()
        self.fc = nn.Linear(cfg.n_embd, 4 * cfg.n_embd)
        self.proj = nn.Linear(4 * cfg.n_embd, cfg.n_embd)
        self.dropout = nn.Dropout(cfg.dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.dropout(self.proj(F.gelu(self.fc(x))))


class Block(nn.Module):
    """One transformer block: pre-norm attention and FFN, each with a residual."""

    def __init__(self, cfg: GPTConfig) -> None:
        super().__init__()
        self.ln1 = nn.LayerNorm(cfg.n_embd)
        self.attn = CausalSelfAttention(cfg)
        self.ln2 = nn.LayerNorm(cfg.n_embd)
        self.mlp = MLP(cfg)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = x + self.attn(self.ln1(x))
        x = x + self.mlp(self.ln2(x))
        return x


class TinyGPT(nn.Module):
    """A small decoder-only language model: embeddings -> blocks -> LM head."""

    def __init__(self, cfg: GPTConfig) -> None:
        super().__init__()
        self.cfg = cfg
        self.block_size = cfg.block_size
        self.token_embed = nn.Embedding(cfg.vocab_size, cfg.n_embd)
        self.pos_embed = nn.Embedding(cfg.block_size, cfg.n_embd)
        self.drop = nn.Dropout(cfg.dropout)
        self.blocks = nn.ModuleList([Block(cfg) for _ in range(cfg.n_layer)])
        self.ln_f = nn.LayerNorm(cfg.n_embd)
        self.lm_head = nn.Linear(cfg.n_embd, cfg.vocab_size, bias=False)
        self.lm_head.weight = self.token_embed.weight
        self.apply(self._init_weights)

    def _init_weights(self, module: nn.Module) -> None:
        if isinstance(module, nn.Linear):
            nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, idx: torch.Tensor) -> torch.Tensor:
        B, T = idx.shape
        pos = torch.arange(T, dtype=torch.long, device=idx.device)
        x = self.drop(self.token_embed(idx) + self.pos_embed(pos))
        for block in self.blocks:
            x = block(x)
        x = self.ln_f(x)
        return self.lm_head(x)

    def num_params(self) -> int:
        return sum(p.numel() for p in self.parameters())


# ---------------------------------------------------------------------------
# LoRA machinery
# ---------------------------------------------------------------------------


class LoRALinear(nn.Module):
    """A frozen Linear wrapped with a low-rank trainable update.

    forward returns base(x) + scale * B A dropout(x).
    B is initialized to zero so the adapter starts as a no-op.
    """

    def __init__(self, base: nn.Linear, r: int, alpha: float, dropout: float = 0.0) -> None:
        super().__init__()
        self.base = base
        self.base.weight.requires_grad = False
        if self.base.bias is not None:
            self.base.bias.requires_grad = False
        self.r = r
        self.alpha = alpha
        self.scale = alpha / r
        in_features = base.in_features
        out_features = base.out_features
        self.A = nn.Parameter(torch.empty(r, in_features))
        self.B = nn.Parameter(torch.empty(out_features, r))
        self.dropout = nn.Dropout(dropout) if dropout > 0.0 else nn.Identity()
        nn.init.normal_(self.A, mean=0.0, std=0.02)
        nn.init.zeros_(self.B)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        base_out = self.base(x)
        # Student step 5: compute the low-rank delta.
        delta = lora_forward_delta(x, self.A, self.B, self.scale, self.dropout)
        return base_out + delta

    def extra_repr(self) -> str:
        return f"r={self.r}, alpha={self.alpha}, scale={self.scale:.4f}"


def inject_lora(
    model: nn.Module,
    r: int,
    alpha: float,
    targets: tuple[str, ...] = ("c_attn", "c_proj", "fc", "proj"),
    dropout: float = 0.0,
) -> None:
    """Walk modules, replacing each named nn.Linear matching `targets` with a LoRALinear wrapper."""
    for name, module in model.named_modules():
        if isinstance(module, nn.Linear):
            last = name.rsplit(".", 1)[-1]
            if last in targets:
                parent_name, child_name = name.rsplit(".", 1)
                parent = model.get_submodule(parent_name)
                setattr(parent, child_name, LoRALinear(module, r, alpha, dropout))


def freeze_base_(model: nn.Module) -> None:
    """Freeze every parameter that does NOT belong to a LoRA adapter."""
    for name, p in model.named_parameters():
        if "A" not in name and "B" not in name:
            # Student step 6: freeze this parameter.
            freeze_base_param(p)


def merge_lora(model: nn.Module) -> nn.Module:
    """Replace every LoRALinear with a plain nn.Linear containing the merged weight."""
    for name, module in model.named_modules():
        if isinstance(module, LoRALinear):
            parent_name, child_name = name.rsplit(".", 1)
            parent = model.get_submodule(parent_name)
            merged_W = merge_lora_weight(module.base.weight.data, module.A.data, module.B.data, module.scale)
            new_linear = nn.Linear(module.base.in_features, module.base.out_features,
                                   bias=module.base.bias is not None)
            with torch.no_grad():
                new_linear.weight.copy_(merged_W)
                if module.base.bias is not None:
                    new_linear.bias.copy_(module.base.bias.data)
            setattr(parent, child_name, new_linear)
    return model


def load_base_model(ckpt_path: str | Path, new_vocab_size: int) -> tuple[TinyGPT, dict[str, int], dict[int, str]]:
    """Load a base checkpoint, expand the vocab for special tokens, keep weight tying."""
    ckpt = torch.load(ckpt_path, weights_only=False)
    raw_cfg = ckpt["config"]
    if isinstance(raw_cfg, dict):
        old_cfg = GPTConfig(**raw_cfg)
    else:
        old_cfg = raw_cfg
    old_vocab = old_cfg.vocab_size
    cfg = GPTConfig(
        vocab_size=new_vocab_size,
        block_size=old_cfg.block_size,
        n_layer=old_cfg.n_layer,
        n_head=old_cfg.n_head,
        n_embd=old_cfg.n_embd,
        dropout=0.0,
    )
    model = TinyGPT(cfg)
    # Filter out size-mismatched keys (token_embed and lm_head grow with vocab).
    sd = ckpt["state_dict"]
    model_sd = model.state_dict()
    filtered = {k: v for k, v in sd.items() if k in model_sd and model_sd[k].shape == v.shape}
    model.load_state_dict(filtered, strict=False)
    # Copy the old vocab rows into the larger tied embedding/head table.
    with torch.no_grad():
        model.token_embed.weight[:old_vocab, :].copy_(sd["token_embed.weight"])
    return model, ckpt["stoi"], ckpt["itos"]


@torch.no_grad()
def generate(
    model: nn.Module,
    idx: torch.Tensor,
    max_new_tokens: int,
    block_size: int,
    temperature: float = 1.0,
    generator: torch.Generator | None = None,
) -> torch.Tensor:
    """Autoregressively extend idx by sampling max_new_tokens new tokens."""
    model.eval()
    for _ in range(max_new_tokens):
        idx_cond = idx[:, -block_size:]
        logits = model(idx_cond)
        logits = logits[:, -1, :] / temperature
        probs = F.softmax(logits, dim=-1)
        next_id = torch.multinomial(probs, num_samples=1, generator=generator)
        idx = torch.cat([idx, next_id], dim=1)
    return idx
