"""
Module 12 attention helpers (PROVIDED; you do not edit this file).

Three things live here:

  softmax_attention  the Module 3 baseline, the thing linear attention is
                     being compared against. Written out in full so you can
                     see that the only real difference is the softmax.
  run_recurrent      the loop that drives your per-token functions from steps
                     4 and 5 across a whole sequence. The loop is plumbing;
                     the two functions it calls are the exercise.
  make_inputs        random Q, K, V from a fixed seed, so every run of this
                     exercise produces exactly the same numbers.
"""

from __future__ import annotations

import torch


def softmax_attention(Q: torch.Tensor, K: torch.Tensor, V: torch.Tensor) -> torch.Tensor:
    """Standard causal softmax attention, exactly as in Module 3.

    Args:
        Q: Queries, shape (n, d).
        K: Keys, shape (n, d).
        V: Values, shape (n, d_v).

    Returns:
        The attention output, shape (n, d_v).
    """
    d = Q.shape[-1]
    # Scaled dot-product scores: every query against every key.
    scores = (Q @ K.transpose(-2, -1)) / (d ** 0.5)
    # Causal masking the softmax way: -inf becomes exactly 0 after exp().
    n = Q.shape[-2]
    causal = torch.tril(torch.ones(n, n, dtype=torch.bool, device=Q.device))
    scores = scores.masked_fill(~causal, float("-inf"))
    # The softmax is the entire difference between this and linear attention.
    weights = torch.softmax(scores, dim=-1)
    return weights @ V


def run_recurrent(
    Q: torch.Tensor,
    K: torch.Tensor,
    V: torch.Tensor,
    feature_map,
    update_state,
    recurrent_step_output,
) -> torch.Tensor:
    """Drive the student's per-token functions across a whole sequence.

    This is the RNN loop: one token at a time, carrying a fixed-size state
    forward. Nothing here depends on the sequence length except the number of
    iterations, which is the entire point.

    Args:
        Q: Queries, shape (n, d).
        K: Keys, shape (n, d).
        V: Values, shape (n, d_v).
        feature_map: The student's step 1.
        update_state: The student's step 4.
        recurrent_step_output: The student's step 5.

    Returns:
        The attention output, shape (n, d_v), stacked over positions.
    """
    n, d = Q.shape
    d_v = V.shape[-1]
    # Feature-map everything once up front; the loop just indexes into these.
    q_phi = feature_map(Q)
    k_phi = feature_map(K)
    # The fixed-size state. These two tensors are all the model will remember.
    S = torch.zeros(d, d_v, dtype=Q.dtype, device=Q.device)
    z = torch.zeros(d, dtype=Q.dtype, device=Q.device)
    outputs = []
    for t in range(n):
        # Absorb token t, then read token t's output back out.
        S, z = update_state(S, z, k_phi[t], V[t])
        outputs.append(recurrent_step_output(q_phi[t], S, z))
    return torch.stack(outputs)


def make_inputs(
    n: int, d: int = 64, seed: int = 0, dtype: torch.dtype = torch.float32
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """Build reproducible random queries, keys, and values.

    There is no dataset in this exercise. We are measuring a property of the
    arithmetic, not of any text, so random tensors of the right shape are
    exactly as informative as real ones and far easier to reason about.

    Args:
        n: Sequence length.
        d: Query and key dimension.
        seed: Fixed so runs are reproducible.
        dtype: Float precision to generate at.

    Returns:
        A (Q, K, V) triple, each shaped (n, d).
    """
    generator = torch.Generator().manual_seed(seed)
    Q = torch.randn(n, d, generator=generator, dtype=dtype)
    K = torch.randn(n, d, generator=generator, dtype=dtype)
    V = torch.randn(n, d, generator=generator, dtype=dtype)
    return Q, K, V
