"""
Module 12 plotting (PROVIDED; you do not edit this file).

One figure: runtime against sequence length for the three implementations, on
log-log axes. The axes are the argument. On a log-log plot a power law is a
straight line whose slope is the exponent, so softmax attention and the
parallel linear form come out near slope 2 (quadratic) and the recurrent form
comes out near slope 1 (linear). The recurrent line starts far above the others
because a Python loop has enormous per-step overhead, and then crosses them,
which is the honest shape of the result: linear beats quadratic eventually, not
immediately. Matplotlib uses the non-interactive Agg backend so it runs
headless on a laptop.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

SERIES_COLORS = {
    "softmax attention (parallel)": "#1f6feb",
    "linear attention (parallel)": "#d29922",
    "linear attention (recurrent)": "#2da44e",
}


def save_scaling_plot(
    lengths: list[int],
    series: dict[str, list[float]],
    out_path: str | Path,
) -> None:
    """Log-log plot of runtime against sequence length.

    Args:
        lengths: Sequence lengths on the x axis.
        series: Maps an implementation's label to its per-length runtimes in
            milliseconds. A None entry means that length was not measured.
        out_path: Where to write the PNG.
    """
    fig, ax = plt.subplots(figsize=(8, 4.8), dpi=120)

    for label, timings in series.items():
        # Drop lengths that were skipped for this implementation.
        xs = [n for n, t in zip(lengths, timings) if t is not None]
        ys = [t for t in timings if t is not None]
        if not xs:
            continue
        ax.plot(
            xs,
            ys,
            marker="o",
            markersize=5,
            linewidth=2,
            color=SERIES_COLORS.get(label),
            label=label,
        )

    ax.set_xscale("log", base=2)
    ax.set_yscale("log")
    ax.set_xlabel("sequence length (tokens)")
    ax.set_ylabel("time per forward pass (ms)")
    ax.set_title("Cost of one forward pass, log-log")
    ax.set_xticks(lengths)
    ax.set_xticklabels([str(n) for n in lengths])
    ax.grid(True, which="both", linewidth=0.4, alpha=0.4)
    ax.legend(frameon=False, loc="upper left")

    fig.tight_layout()
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path)
    plt.close(fig)
