"""
Module 7 plotting (PROVIDED — you do not edit this file).

Saves the reward curve from a GRPO run: mean group reward versus training step,
with the before/after held-out accuracy drawn in for context. Matplotlib uses the
non-interactive Agg backend so it runs headless on a laptop.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402


def save_reward_curve(
    steps: list[int],
    rewards: list[float],
    out_path: str | Path,
    acc_before: float | None = None,
    acc_after: float | None = None,
) -> None:
    """Plot mean group reward over training and save it to out_path."""
    fig, ax = plt.subplots(figsize=(8, 4.5), dpi=120)
    ax.plot(steps, rewards, color="#1f6feb", linewidth=2, label="mean group reward")
    ax.set_xlabel("GRPO step")
    ax.set_ylabel("mean reward (fraction correct)")
    ax.set_title("GRPO reward curve: reward climbs as the policy learns to verify")
    ax.set_ylim(-0.02, 1.02)
    ax.grid(True, alpha=0.3)

    if acc_before is not None:
        ax.axhline(acc_before, color="#999999", linestyle="--", linewidth=1,
                   label=f"held-out acc before: {acc_before:.0%}")
    if acc_after is not None:
        ax.axhline(acc_after, color="#2da44e", linestyle="--", linewidth=1,
                   label=f"held-out acc after: {acc_after:.0%}")

    ax.legend(loc="lower right", framealpha=0.9)
    fig.tight_layout()
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path)
    plt.close(fig)
