"""
Module 5: the tiny GPT model (PROVIDED — you do not edit this file).

This is a scaled-down version of the decoder-only transformer you assembled in
Module 4: token + position embeddings, a few transformer blocks, a final norm,
and a language-modeling head. It is small enough to train from scratch on a
laptop CPU in a few minutes.

In Module 5 the architecture is the *fixed* part. Your job (in `exercise.py`) is
the PRETRAINING LOOP that turns this model's random weights into useful ones.

`forward(idx)` takes a batch of token IDs of shape (batch, time) and returns
logits of shape (batch, time, vocab_size): one score per vocabulary token, at
every position. Computing the loss from those logits is your Step 4.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F


@dataclass
class GPTConfig:
    """All the knobs that define the model's size."""
    vocab_size: int          # how many distinct tokens (here: distinct characters)
    block_size: int = 128    # context length: how many tokens the model can see at once
    n_layer: int = 4         # how many transformer blocks are stacked
    n_head: int = 4          # how many attention heads per block
    n_embd: int = 128        # width of each token vector (the model dimension)
    dropout: float = 0.1     # dropout probability used during training


class CausalSelfAttention(nn.Module):
    """Multi-head self-attention with a causal mask (no peeking at the future)."""

    def __init__(self, cfg: GPTConfig) -> None:
        super().__init__()
        assert cfg.n_embd % cfg.n_head == 0
        self.n_head = cfg.n_head
        self.n_embd = cfg.n_embd
        # One linear layer produces the query, key, and value for every head at once.
        self.c_attn = nn.Linear(cfg.n_embd, 3 * cfg.n_embd)
        # The output projection that mixes the heads back together.
        self.c_proj = nn.Linear(cfg.n_embd, cfg.n_embd)
        self.attn_dropout = nn.Dropout(cfg.dropout)
        self.resid_dropout = nn.Dropout(cfg.dropout)
        # A lower-triangular matrix of ones: row t allows columns 0..t (the past).
        self.register_buffer(
            "mask",
            torch.tril(torch.ones(cfg.block_size, cfg.block_size)).view(
                1, 1, cfg.block_size, cfg.block_size
            ),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        B, T, C = x.shape  # batch, time (tokens), channels (n_embd)
        # Project to query/key/value and split into the three tensors.
        q, k, v = self.c_attn(x).split(self.n_embd, dim=2)
        # Reshape each into (B, n_head, T, head_size) so heads attend in parallel.
        head_size = C // self.n_head
        q = q.view(B, T, self.n_head, head_size).transpose(1, 2)
        k = k.view(B, T, self.n_head, head_size).transpose(1, 2)
        v = v.view(B, T, self.n_head, head_size).transpose(1, 2)
        # Scaled dot-product scores between every query and key.
        att = (q @ k.transpose(-2, -1)) * (1.0 / math.sqrt(head_size))
        # Block attention to future positions by setting those scores to -infinity.
        att = att.masked_fill(self.mask[:, :, :T, :T] == 0, float("-inf"))
        att = F.softmax(att, dim=-1)            # turn scores into weights that sum to 1
        att = self.attn_dropout(att)
        y = att @ v                              # weighted sum of value vectors
        # Recombine the heads and project back to the model dimension.
        y = y.transpose(1, 2).contiguous().view(B, T, C)
        return self.resid_dropout(self.c_proj(y))


class MLP(nn.Module):
    """Position-wise feed-forward network: widen to 4x, GELU, project back."""

    def __init__(self, cfg: GPTConfig) -> None:
        super().__init__()
        self.fc = nn.Linear(cfg.n_embd, 4 * cfg.n_embd)
        self.proj = nn.Linear(4 * cfg.n_embd, cfg.n_embd)
        self.dropout = nn.Dropout(cfg.dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.dropout(self.proj(F.gelu(self.fc(x))))


class Block(nn.Module):
    """One transformer block: pre-norm attention and FFN, each with a residual."""

    def __init__(self, cfg: GPTConfig) -> None:
        super().__init__()
        self.ln1 = nn.LayerNorm(cfg.n_embd)
        self.attn = CausalSelfAttention(cfg)
        self.ln2 = nn.LayerNorm(cfg.n_embd)
        self.mlp = MLP(cfg)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # Add each sub-layer's output back onto the running "residual stream".
        x = x + self.attn(self.ln1(x))
        x = x + self.mlp(self.ln2(x))
        return x


class TinyGPT(nn.Module):
    """A small decoder-only language model: embeddings -> blocks -> LM head."""

    def __init__(self, cfg: GPTConfig) -> None:
        super().__init__()
        self.cfg = cfg
        self.block_size = cfg.block_size
        # One learned vector per vocabulary token, and one per position.
        self.token_embed = nn.Embedding(cfg.vocab_size, cfg.n_embd)
        self.pos_embed = nn.Embedding(cfg.block_size, cfg.n_embd)
        self.drop = nn.Dropout(cfg.dropout)
        self.blocks = nn.ModuleList([Block(cfg) for _ in range(cfg.n_layer)])
        self.ln_f = nn.LayerNorm(cfg.n_embd)
        # Maps the final vector back to one score per vocabulary token.
        self.lm_head = nn.Linear(cfg.n_embd, cfg.vocab_size, bias=False)
        # Weight tying: the embedding table and the output head share weights.
        self.lm_head.weight = self.token_embed.weight
        self.apply(self._init_weights)

    def _init_weights(self, module: nn.Module) -> None:
        # Small random initialization, the standard GPT-style scheme.
        if isinstance(module, nn.Linear):
            nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, idx: torch.Tensor) -> torch.Tensor:
        """Map a batch of token IDs (B, T) to logits (B, T, vocab_size)."""
        B, T = idx.shape
        # Positions 0, 1, ..., T-1 for this block.
        pos = torch.arange(T, dtype=torch.long, device=idx.device)
        # Each token's vector is its content embedding plus its position embedding.
        x = self.drop(self.token_embed(idx) + self.pos_embed(pos))
        for block in self.blocks:
            x = block(x)
        x = self.ln_f(x)
        return self.lm_head(x)

    def num_params(self) -> int:
        """Total number of parameters (the embedding/head are tied, so count once)."""
        return sum(p.numel() for p in self.parameters())
